# Generated by Django 5.0.3 on 2024-04-02 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('description', models.CharField(max_length=64)),
                ('slug', models.SlugField()),
                ('thumbnail', models.ImageField(upload_to='')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.TimeField(auto_now=True)),
            ],
        ),
    ]
